[build]
  publish = "."
  functions = "netlify/functions"
  # no build command needed because you're serving raw HTML

# optional: use esbuild to bundle functions
[functions]
  node_bundler = "esbuild"
  included_files = ["data/*.json"]
